import { ImageResponse } from "next/og";
import { readFile } from "fs/promises";
import { join } from "path";

/**
 * Open Graph + Twitter card image for ace-presenter.app.
 *
 * Generated by next/og — Next.js automatically wires the output PNG into
 * <meta property="og:image"> and <meta name="twitter:image"> for every
 * page that doesn't override them. 1200×630 is the standard Facebook /
 * LinkedIn / Slack / iMessage card size; Twitter `summary_large_image`
 * accepts the same dimensions.
 *
 * Implementation note: next/og uses Satori under the hood, which has
 * stricter rules than the browser:
 *   - Every <div> with more than one child needs explicit display: flex
 *   - z-index is not honoured (use document order for stacking)
 *   - <span> children are fine inside a flex div as long as the parent
 *     itself is flex
 */

export const runtime = "nodejs";
export const alt = "ACE — Agentic Cue Experience";
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

export default async function OGImage() {
  const logoPath = join(process.cwd(), "public", "logo-large.png");
  const logoBuffer = await readFile(logoPath);
  const logoSrc = `data:image/png;base64,${logoBuffer.toString("base64")}`;

  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          flexDirection: "column",
          background: "#0F0F0F",
          padding: 80,
          position: "relative",
        }}
      >
        {/* Bottom-left brand glow */}
        <div
          style={{
            display: "flex",
            position: "absolute",
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            background:
              "radial-gradient(60% 60% at 0% 100%, rgba(200,16,46,0.35) 0%, rgba(200,16,46,0) 65%)",
          }}
        />
        {/* Top-right accent glow */}
        <div
          style={{
            display: "flex",
            position: "absolute",
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            background:
              "radial-gradient(40% 50% at 100% 0%, rgba(232,24,58,0.18) 0%, rgba(232,24,58,0) 65%)",
          }}
        />

        {/* Top row — logo + wordmark */}
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: 24,
          }}
        >
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src={logoSrc}
            alt="ACE"
            width={88}
            height={88}
            style={{ borderRadius: 18 }}
          />
          <div
            style={{
              display: "flex",
              color: "white",
              fontSize: 56,
              fontWeight: 800,
              letterSpacing: "-0.02em",
            }}
          >
            ACE
          </div>
        </div>

        {/* Spacer */}
        <div style={{ display: "flex", flex: 1 }} />

        {/* Headline block */}
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            color: "white",
          }}
        >
          {/* Acronym tag */}
          <div
            style={{
              display: "flex",
              fontSize: 24,
              fontWeight: 600,
              letterSpacing: "0.18em",
              textTransform: "uppercase",
              color: "#E8183A",
              marginBottom: 24,
            }}
          >
            Agentic Cue Experience
          </div>

          {/* "ACE listens." line */}
          <div
            style={{
              display: "flex",
              fontSize: 96,
              fontWeight: 800,
              lineHeight: 1,
              letterSpacing: "-0.03em",
              color: "white",
            }}
          >
            ACE listens.
          </div>

          {/* "You present." line — split into two flex children for
              the colour transition without using inline text+span mix */}
          <div
            style={{
              display: "flex",
              alignItems: "baseline",
              fontSize: 96,
              fontWeight: 800,
              lineHeight: 1,
              letterSpacing: "-0.03em",
              marginTop: 8,
            }}
          >
            <div style={{ display: "flex", color: "white" }}>You&nbsp;</div>
            <div
              style={{
                display: "flex",
                color: "#E8183A",
                fontStyle: "italic",
                fontWeight: 600,
              }}
            >
              present.
            </div>
          </div>

          {/* Subtitle */}
          <div
            style={{
              display: "flex",
              marginTop: 32,
              fontSize: 28,
              color: "#C4C4C4",
              maxWidth: 900,
            }}
          >
            AI-powered live presentation for worship, conferences, lectures, and theater.
          </div>
        </div>

        {/* Bottom row — domain */}
        <div
          style={{
            display: "flex",
            justifyContent: "flex-end",
            marginTop: 40,
          }}
        >
          <div
            style={{
              display: "flex",
              fontSize: 22,
              color: "#888",
              letterSpacing: "0.05em",
            }}
          >
            ace-presenter.app
          </div>
        </div>
      </div>
    ),
    { ...size }
  );
}
