// Regenerates src/app/manual/manual.generated.ts from content/manual/*.md.
// Run locally after editing the manual: `node scripts/build-manual.mjs`
// (requires pandoc). The generated module is committed so Vercel needs no pandoc.
import { execSync } from 'child_process';
import { writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, resolve } from 'path';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const dir = resolve(root, 'content/manual');

const files = [
  ['README.md', 'Overview', ''],
  ['01-getting-started.md', 'Getting Started', '1'],
  ['02-service-and-cues.md', 'Cues & Running Order', '2'],
  ['03-songs-and-arrangements.md', 'Songs & Arrangements', '3'],
  ['04-scripture.md', 'Scripture', '4'],
  ['05-detection-ai.md', 'Detection & Auto-Follow', '5'],
  ['06-media.md', 'Media', '6'],
  ['07-themes-looks-overlays.md', 'Themes, Looks & Overlays', '7'],
  ['08-outputs-and-screens.md', 'Outputs & Screens', '8'],
  ['09-streaming-and-audio.md', 'Streaming & Audio', '9'],
  ['10-remote-control.md', 'The Phone Remote', '10'],
  ['11-preferences-shortcuts.md', 'Preferences & Shortcuts', '11'],
  ['appendix-a-platform-differences.md', 'A · Platform Differences', 'A'],
  ['appendix-b-keyboard-shortcuts.md', 'B · Keyboard Shortcuts', 'B'],
  ['appendix-c-dependencies.md', 'C · Dependencies', 'C'],
];
const anchor = (fn) => 'sec-' + fn.replace(/\.md$/, '');

// The manual is framed like an ACE run-of-show: each chapter is a "cue".
const cueLabel = (num) =>
  num === '' ? 'Start here' : /^[0-9]+$/.test(num) ? `Cue ${num}` : `Appendix ${num}`;

let html = '';
for (const [fn, , num] of files) {
  let frag = execSync(`pandoc --from gfm --to html5 "${dir}/${fn}"`, { encoding: 'utf8', maxBuffer: 1e7 });
  frag = frag.replace(/href="([0-9a-zA-Z-]+)\.md(#[^"]*)?"/g, (_m, base) => `href="#sec-${base}"`);
  if (fn === 'README.md') frag = frag.replace(/<h2[^>]*>Table of contents<\/h2>[\s\S]*?<\/ul>/i, '');
  const cue = `<div class="doc-cue"><span class="cue-rule" aria-hidden="true"></span><span class="cue-tag">${cueLabel(num)}</span></div>`;
  html += `<section id="${anchor(fn)}" class="doc" data-num="${num}">\n${cue}\n${frag}\n</section>\n`;
}

const badges = [
  ['(both)', 'both', 'both'],
  ['(macOS only)', 'mac', 'macOS only'],
  ['(Windows: not yet available)', 'winno', 'Windows — not yet'],
  ['(build-dependent)', 'build', 'build-dependent'],
  ['(Pro)', 'pro', 'Pro'],
  ['(Windows only)', 'win', 'Windows only'],
];
for (const [needle, cls, label] of badges) {
  html = html.split(needle).join(`<span class="badge b-${cls}">${label}</span>`);
}

const nav = files.map(([fn, title, num]) => ({ id: anchor(fn), title, num }));

const out = `// AUTO-GENERATED by scripts/build-manual.mjs — do not edit by hand.
// Source: content/manual/*.md. Regenerate with: node scripts/build-manual.mjs
export type ManualNavItem = { id: string; title: string; num: string };
export const MANUAL_NAV: ManualNavItem[] = ${JSON.stringify(nav, null, 2)};
export const MANUAL_HTML: string = ${JSON.stringify(html)};
`;
writeFileSync(resolve(root, 'src/app/manual/manual.generated.ts'), out);
console.log('wrote src/app/manual/manual.generated.ts —', html.length, 'chars of HTML,', nav.length, 'sections');
